---
apiVersion: v1
kind: Secret
metadata:
  name: cognito-secrets
  namespace: default
type: Opaque
stringData:
  COGNITO_DOMAIN: "REPLACE_WITH_YOUR_COGNITO_DOMAIN"
  COGNITO_CLIENT_ID: "REPLACE_WITH_YOUR_CLIENT_ID"
  COGNITO_CLIENT_SECRET: "REPLACE_WITH_YOUR_CLIENT_SECRET"
  SECRET_KEY: "REPLACE_WITH_RANDOM_SECRET_KEY"
