apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-logs-viewer-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/CloudWatchLogsViewerRole
