apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-logs-viewer
  namespace: default
  labels:
    app: cloudwatch-logs-viewer
spec:
  type: NodePort
  selector:
    app: cloudwatch-logs-viewer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
